name: Continuous Integration

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
  pipeline:
    runs-on: [windows-latest]

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-dotnet@master

      - name: Build Solution
        run: dotnet build --configuration Release
      
      - name: Create Test Binaries
        working-directory: Lunar.Tests\TestBinaries
        run: |
             mkdir bin\x86
             mkdir bin\x64
             cmake -A Win32 -B bin\x86
             cmake -A x64 -B bin\x64
             cmake --build bin\x86 --config Release
             cmake --build bin\x64 --config Release
        
      - name: Run Tests
        run: dotnet test
      
      - name: Create Package
        run: dotnet pack Lunar --configuration Release
      
      - uses: actions/setup-dotnet@master
        with:
            source-url: https://nuget.pkg.github.com/${{github.actor}}
        env:
            NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Publish Package
        run: dotnet nuget push 'Lunar\bin\Release\*.nupkg' --skip-duplicate